// This file is automatically generated from your CSS. Any edits will be overwritten.
export const job__image: string;
export const jobImage: string;
export const sizeRegular: string;
export const sizeSmall: string;
export const job__hoverable: string;
export const jobHoverable: string;
