// This file is automatically generated from your CSS. Any edits will be overwritten.
export const self: string;
export const wrapper: string;
export const upperLayer: string;
export const blurred: string;
export const aboveHeader: string;
