// This file is automatically generated from your CSS. Any edits will be overwritten.
export const battle: string;
export const accompaniment: string;
export const faceHintContainer: string;
export const faceHint: string;
export const faceHintShadow: string;
