// This file is automatically generated from your CSS. Any edits will be overwritten.
export const autoAdvanceButton: string;
export const label: string;
export const progressBarContainer: string;
export const progressBarFill: string;
