// This file is automatically generated from your CSS. Any edits will be overwritten.
export const grandTotal: string;
export const grandTotalAmount: string;
export const job__list: string;
export const jobList: string;
export const job: string;
export const jobImageContainer: string;
export const job__image: string;
export const jobImage: string;
export const jobEarningsContainer: string;
export const job__earnings: string;
export const jobEarnings: string;
export const job__trait: string;
export const jobTrait: string;
export const chooseJobContainer: string;
export const content: string;
