// This file is automatically generated from your CSS. Any edits will be overwritten.
export const jobSummaryContainer: string;
export const jobSummaryBody: string;
export const job__image: string;
export const jobImage: string;
export const job__review: string;
export const jobReview: string;
export const jobSummaryImageReview: string;
export const jobSummaryLineItem: string;
export const jobSummaryLineItemsSeparator: string;
export const jobSummaryGrandTotalContainer: string;
export const jobSummaryGrandTotalHeader: string;
export const jobSummaryFooter: string;
export const jobSummaryFooterMessage: string;
export const hidden: string;
export const jobSummaryFooterPadding: string;
