// This file is automatically generated from your CSS. Any edits will be overwritten.
export const ratingGauge: string;
export const ratingGaugeWhite: string;
export const ratingGaugeGreen: string;
export const ratingGaugeContainer: string;
export const ratingGaugeCommentContainer: string;
export const ratingGaugeComment: string;
export const ratingGaugeCommentOnly: string;
export const fade: string;
export const ratingGaugeValue: string;
export const pop: string;
export const ratingGaugeHighScore: string;
