// This file is automatically generated from your CSS. Any edits will be overwritten.
export const versus: string;
export const videoSelfieWrapper: string;
export const flexRowWrap: string;
export const accompaniment: string;
export const selfieStatus: string;
